XYZCorpTempSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RTE;
using XYZCorpTempSite.Contexts;
using XYZCorpTempSite.Interfaces;
using XYZCorpTempSite.Models;
using XYZCorpTempSite.Repositories;

namespace XYZCorpTempSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRepository _repository;
        private IRepository Repository { get { return _repository;} }

        public HomeController(IRepository repository)
        {
            if (repository == null)
            {
                throw new ArgumentNullException("repository");
            }
            _repository = repository;
        }
        public ActionResult Index()
        {
            using (var db = new NewsContext())
            {
                var featuredArticle = (NewsArticle)Repository.GetFeaturedArticle(db);
                var articles = (List<NewsArticle>)Repository.GetArticles(db);
                articles.Remove(featuredArticle);

                //SeedData(db);
                return View(new HomePage
                {
                    Articles = articles,
                    FeaturedArticle = featuredArticle,
                    XyzCorpLogo = Repository.GetCurrentLogo(db)
                });
            }
        }

        private void SeedData(NewsContext db)
        {
            //db.Logos.Add(new Logo
            //{
            //    IsCurrent = true,
            //    Alt = "current-xyzCorp-logo",
            //    Src = @"C:\Users\Architect\documents\visual studio 2013\Projects\XYZCorpTempSite\XYZCorpTempSite\Content\Resources\XYZ_Logo_Generic.jpg"
            //});

            db.NewsArticles.Add(new NewsArticle
            {
                Content = "<div class='col-md-12'><h6>This is a content byLine!</h6></div>"
                + "<div class='col-md-12'><p>This is a bunch of content relating to XYZ News!</p>",
                Header = "XYZ Breaking News Update 12/31/1600",
                IsFeatured = true
            });
            db.SaveChanges();
        }

        [Authorize]
        public ActionResult Edit()
        {
            using (var db = new NewsContext())
            {
                var homePage = new HomePage
                {
                    Articles = Repository.GetArticles(db),
                    FeaturedArticle = Repository.GetFeaturedArticle(db),
                    XyzCorpLogo = Repository.GetCurrentLogo(db)
                };
                return View(homePage);
            }
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

XYZCorpTempSite/Controllers/NewsArticlesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using RTE;
using XYZCorpTempSite.Contexts;
using XYZCorpTempSite.Models;

namespace XYZCorpTempSite.Controllers
{
    [Authorize]
    public class NewsArticlesController : Controller
    {
        
        private NewsContext db = new NewsContext();

        // GET: NewsArticles
        public ActionResult Index()
        {
            return View(db.NewsArticles.ToList());
        }

        // GET: NewsArticles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsArticle newsArticle = db.NewsArticles.Find(id);
            if (newsArticle == null)
            {
                return HttpNotFound();
            }
            return View(newsArticle);
        }

        // GET: NewsArticles/Create
        public ActionResult Create()
        {
            var newsEditorModel = new NewsEditorModel
            {
                Editor = new Editor(System.Web.HttpContext.Current, "NewsEditor"),
                SelectedArticle = new NewsArticle()
            };

            newsEditorModel.Editor.LoadFormData(string.Empty);
            newsEditorModel.Editor.MvcInit();

            return View(newsEditorModel);
        }

        // POST: NewsArticles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost][ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NewsArticleId,Header,IsFeatured, NewsEditor")] NewsArticle newsArticle)
        {
            newsArticle.Content = newsArticle.NewsEditor;

            if (ModelState.IsValid)
            {
                db.NewsArticles.Add(newsArticle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var newsEditorModel = new NewsEditorModel
            {
                Editor = new Editor(System.Web.HttpContext.Current, "NewsEditor"),
                SelectedArticle = newsArticle
            };

            newsEditorModel.Editor.LoadFormData(newsArticle.Content);
            newsEditorModel.Editor.MvcInit();

            return View(newsEditorModel);
        }

        // GET: NewsArticles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsArticle newsArticle = db.NewsArticles.Find(id);
            if (newsArticle == null)
            {
                return HttpNotFound();
            }

            var newsEditorModel = new NewsEditorModel
            {
                Editor = new Editor(System.Web.HttpContext.Current, "NewsEditor"),
                SelectedArticle = newsArticle
            };

            newsEditorModel.Editor.LoadFormData(newsArticle.Content);
            newsEditorModel.Editor.MvcInit();

            return View(newsEditorModel);
        }

        // POST: NewsArticles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NewsArticleId,Header,NewsEditor,IsFeatured")] NewsArticle newsArticle)
        {
            newsArticle.Content = newsArticle.NewsEditor;

            if (ModelState.IsValid)
            {
                db.Entry(newsArticle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var newsEditorModel = new NewsEditorModel
            {
                Editor = new Editor(System.Web.HttpContext.Current, "NewsEditor"),
                SelectedArticle = newsArticle
            };

            newsEditorModel.Editor.LoadFormData(newsArticle.Content);
            newsEditorModel.Editor.MvcInit();

            return View(newsEditorModel);
        }

        // GET: NewsArticles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsArticle newsArticle = db.NewsArticles.Find(id);
            if (newsArticle == null)
            {
                return HttpNotFound();
            }
            return View(newsArticle);
        }

        // POST: NewsArticles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewsArticle newsArticle = db.NewsArticles.Find(id);
            db.NewsArticles.Remove(newsArticle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

XYZCorpTempSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

XYZCorpTempSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

XYZCorpTempSite/Views/Home/Edit.cshtml
@using Castle.Core.Internal
@using XYZCorpTempSite.Models
@model XYZCorpTempSite.Interfaces.IHomePage

<div class="col-md-12">
    <h2 class="text-center">Edit News Articles</h2>
    <div class="row">
        @if (!Model.Articles.IsNullOrEmpty())
        {
            foreach (var article in Model.Articles)
            {
                <div class="col-md-12 text-center">
                    <h3>
                        @Html.ActionLink(article.Header ?? "[NO HEADER]", "Edit", "NewsArticles",
                            new {id = ((NewsArticle) article).NewsArticleId}, null)
                    </h3>
                </div>
            }
        }
    </div>
</div>

XYZCorpTempSite/Views/Home/Index.cshtml
@using Castle.Core.Internal
@model XYZCorpTempSite.Interfaces.IHomePage

<div class="jumbotron">
    <img style="width: 25%; margin: 0 auto;" src="@Model.XyzCorpLogo.Src"
         alt="@Model.XyzCorpLogo.Alt"
         class="@Model.XyzCorpLogo.Class"/>
    <span><h2 style="display: inline; padding-left: 10%;">XYZ Corp News</h2></span>

</div>

<div class="row">
    <div class="col-xs-12">
        <h1>@Html.Raw(Model.FeaturedArticle.Header)</h1>
        @Html.Raw(Model.FeaturedArticle.Content)
    </div>
</div>
<hr/>
@if (!Model.Articles.IsNullOrEmpty())
{
    <div class="row">
        @foreach (var article in Model.Articles)
        {
            <div class="col-xs-6 panel">
                <h3>@article.Header</h3>
                @Html.Raw(article.Content)
            </div>
        }
    </div>
}